"""Third migr/change fk

Revision ID: 9486380b889d
Revises: d1e4b1c7f5d1
Create Date: 2021-06-07 23:42:42.367725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9486380b889d'
down_revision = 'd1e4b1c7f5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
